template-file-path: root-stack.yaml
parameters:
  ProjectName: photouploader
  TemplatesBucketName: photouploader-infra-templates-eu-central-1-124355645722
  GitHubOidcProviderArn: arn:aws:iam::124355645722:oidc-provider/token.actions.githubusercontent.com
  GitHubOrg: basit-devBE
  GitHubAppRepo: photouploader-app
  GitHubBranch: main
  # Bootstraps the first ECS service deploy (serves 200 on /actuator/health)
  # until the real pipeline pushes the actual app image via blue/green.
  AppImageUri: 124355645722.dkr.ecr.eu-central-1.amazonaws.com/ecs-lab-bootstrap:latest
  DBInstanceClass: db.t3.micro
  DBName: photouploader
capabilities:
  - CAPABILITY_NAMED_IAM
  - CAPABILITY_AUTO_EXPAND
tags:
  Project: photouploader
  ManagedBy: CloudFormation-GitSync
